### ISSUE TITLE
How to get the real-world depth image

### ISSUE THREAD

**Issue by xielinjiang** [yzcjtr/GeoNet#7]
HI:
Thank you for your work！
I read your code, but I didn't find out how to get a real-world depth image.
Looking forward to your reply.
Thank you！

**Comment by kristijanbartol** [comment]
If you are talking about using KITTI dataset, try [eval_depth.py](https://github.com/yzcjtr/GeoNet/blob/master/kitti_eval/eval_depth.py) on KITTI test data, but change the code so that it saves ground truth disparities to images.

**Comment by xielinjiang** [comment]
Thanks for your answer, how can I change the code?

**Comment by yzcjtr** [comment]
If you mean generating depth map from groundtruth, just follow the suggestion by @kristijanbartol .  Note that they are sparse points. For visualization, you could multiply them with 256 and save to an uint16 png format thereafter.

**Comment by xielinjiang** [comment]
Sorry, I mean is that generating depth map from pred_depth

**Comment by yzcjtr** [comment]
The multi-scale prediction is exactly self.pred_depth. It differs from the real-world depth (in real-world metric) by a scale factor which is unknown. See [here](https://github.com/yzcjtr/GeoNet/blob/cf336f6b91a16997d67c5ca0c6666f0b6700c435/kitti_eval/eval_depth.py#L110-L112) for reference.

**Comment by xielinjiang** [comment]
If so, how do I get the depth of the unknown image?

**Comment by yzcjtr** [comment]
The scale ambiguity can not be resolved unless you have prior knowledge, which is the case in most monocular SLAM methods.

**Comment by yzcjtr** [comment]
They are indeed the depth prediction by our method. They differ from the true depth by a relative scale.

**Comment by kristijanbartol** [comment]
If I understood it correctly, you need [geonet_test_depth.py](https://github.com/yzcjtr/GeoNet/blob/master/geonet_test_depth.py). There you specify a .txt file with images list and you get (depth) predictions for each of these images. To get actual images, just save it to image file instead of storing it to .npy.

**Comment by xielinjiang** [comment]
the depth of predictions for each of these images in the [geonet_test_depth.py](https://github.com/yzcjtr/GeoNet/blob/master/geonet_test_depth.py) is not the true depth.

**Comment by kristijanbartol** [comment]
Ah, I see. That's a bit more tricky. What you get in KITTI dataset are point clouds (velodyne/ directory). You can generate disparity / depth maps from it, but personally I failed to do it.

**Comment by xielinjiang** [comment]
But in most application scenarios, there is no point clouds, so in that application scenarios we can‘t calculate the true depth. so······

**Comment by kristijanbartol** [comment]
In general, it is hard to obtain ground truth for spatial features (depth, optical flow). That's why unsupervised methods are so popular now...

**Comment by yzcjtr** [comment]
If you can't understand the scale ambiguity issue existing in monocular SLAM methods, read more books please. @xielinjiang

**Comment by tongpinmo** [comment]
I have some doubts. Have you tried to use two images as input to predict depth or what's  the advantages and significance of singe-view depth prediction? From the above discussion, there is no true depth for a single image.
one more,I think that single view depth has more problems generalizing to previously unseen types of images. For example ,a model trained on outdoor driving sequences is unlikely to work well on indoor scenes .

**Comment by yzcjtr** [comment]
I haven't tried using two or more images as input to DepthNet. Of course you can try it. Promisingly you will have better generalization ability, but there is no guarantee.
PS, I don't know what you mean by 'there is no true depth for a single image'.

**Comment by kristijanbartol** [comment]
There are two quite different approaches to depth estimation based on the available camera configuration:
- stereo vision (2 cameras giving *rectified* images as input (please check what calibration+rectification actually means. Anyhow, try to understand the fundamental difference between mono and stereo (HINT: having two rectified images and knowing the *corresponding points*, you directly have *disparities*.) Everything further is far away from GeoNet topic.)
- monocular vision (1 camera giving a single image as input)

Of course, you don't always have a calibrated camera system to feed stereo algorithms, so you are only left with a single image. It is actually a fascinating fact that you can use deep learning to estimate depth from single-image sequences (check this [CVPR tutorial](http://www.ee.iisc.ac.in/labs/cvl/papers/tutorial.motion.averaging.pdf) about structure-from-motion in classical, non-deep-learning sense).

> I think that single view depth has more problems generalizing to previously unseen types of images.
This statement regards one of the fundamental questions of deep learning. This is true not only for a single view depth, but for many (almost every) other problem deep learning is trying to solve and you always tend to generalize well and different datasets / sets of problems... But this is really a generic question and answer, please find more relevant materials about deep learning.

> From the above discussion, there is no true depth for a single image.
You are right, what you have given a single image as input are *relative* disparities / depth information. This is, again, because of mentioned scale ambiguity.

I hope I shed some light on your confusion and I warmly suggest [this](https://classroom.udacity.com/courses/ud810) course to answer these and much more of your questions about computer vision.

**Comment by yzcjtr** [comment]
@kristijanbartol Thanks for your detailed and organized explanation. I learn a lot from your answer as well.

**Comment by tongpinmo** [comment]
@kristijanbartol thank you for your detailed explanation. I have learned a lot .Since there is scale ambiguity in single image ,why so many researchers do deep research in it? we can't apply it into the real scene like Automatic Driving,maybe it's a trying or we use deep learning method because of its scale ambiguity? if we can describe it in geometric method ,is it necessary for us to use deep learning?

**Comment by kristijanbartol** [comment]
Check this [paper](http://arxiv.org/abs/1801.04461) (size-to-depth). What I'm saying is that there are ways to recover depth from monocular images, but you need additional information, which is, in this paper, a size of a particular object in the image. Generally, this information is called *prior knowledge*.

>  if we can describe it in geometric method ,is it necessary for us to use deep learning?

Of course it's not necessary. We use it as it's proven to work well (better and faster than classical algorithms) with many interesting problems, including monocular "depth" estimation.

**Comment by tongpinmo** [comment]
ok ,it's very nice of you , I have learned a lot!
